import { Services } from '../models';

export const SERVICES: Services = [
  {
    slug: 'mantenimiento-y-reparacion-de-equipos-especiales',
    title: 'Mantenimiento y Reparación de Equipos Especiales',
    summary:
      'Ejecutamos mantenimiento y reparación de equipos especiales con enfoque preventivo y correctivo, asegurando disponibilidad operativa, seguridad en ruta y mayor vida útil de cada unidad.',
    description:
      '<p>Ofrecemos servicios especializados de mantenimiento y reparación de equipos especiales, orientados a garantizar la confiabilidad, seguridad y continuidad operativa de sus activos.</p><p>Contamos con experiencia en la atención de trailers, compactadoras y equipos de recolección de residuos sólidos, vehículos eléctricos, tolvas graneleras y carrocerías, abarcando intervenciones en sistemas estructurales, mecánicos, hidráulicos y eléctricos.</p><p>Nuestro equipo técnico realiza diagnósticos precisos y aplica soluciones adaptadas a cada tipo de operación, utilizando repuestos de alta calidad y procedimientos estandarizados. Con ello, logramos reducir tiempos de inactividad, optimizar el desempeño en campo y asegurar entregas bajo altos estándares de calidad y seguridad.</p><ul><li><strong>Trailers:</strong> realizamos inspección integral, ajustes estructurales y correcciones mecánicas para mantener estabilidad, seguridad y rendimiento en operación continua.</li><li><strong>Compactadoras y equipos de recolección de desechos sólidos:</strong> intervenimos sistemas de compactación, transmisión y estructura para minimizar fallas y sostener la productividad de recolección.</li><li><strong>Vehículos eléctricos:</strong> atendemos sistemas de tracción, carga, frenado y componentes asociados para asegurar desempeño eficiente y operación segura.</li><li><strong>Tolvas graneleras:</strong> ejecutamos mantenimiento de compuertas, soldaduras, refuerzos y puntos críticos para preservar capacidad de carga y confiabilidad en traslado.</li><li><strong>Carrocerías:</strong> corregimos desgaste, daños estructurales y acabados para recuperar funcionalidad, presentación y durabilidad de la unidad.</li></ul>',
    horizontalImage: '/images/mantenimiento-y-reparacion-de-equipos-especiales.webp',
    verticalImage: '/images/mantenimiento-y-reparacion-de-equipos-especiales-vertical.webp',
  },
  {
    slug: 'colision',
    title: 'Colisión y Recuperación de Equipos Especiales',
    summary:
      'Atendemos servicios de colisión con procesos técnicos integrales para devolver seguridad, geometría y acabado estético a la unidad, reduciendo tiempos de inmovilización.',
    description:
      '<p>Ofrecemos servicios especializados de atención de colisiones y siniestros para equipos especiales, enfocados en la recuperación integral de las unidades y su retorno seguro a operación.</p><p>Contamos con experiencia en la reparación de trailers, compactadoras y equipos de recolección de residuos sólidos, vehículos eléctricos, tolvas graneleras y carrocerías, atendiendo daños estructurales y funcionales derivados de accidentes o eventos operativos.</p><p>Nuestro servicio incluye reparaciones en fibra de vidrio y plástico, trabajos de latonería, pintura y procesos de reconstrucción, ejecutados por personal calificado bajo estándares técnicos rigurosos. Realizamos diagnósticos detallados para definir el alcance de cada intervención, garantizando acabados de alta calidad, recuperación de la integridad estructural y óptimas condiciones operativas.</p><p>Nos enfocamos en reducir tiempos de inmovilización, optimizar costos de reparación y asegurar resultados confiables, alineados con altos estándares de calidad y seguridad.</p><ul><li><strong>Reparaciones en fibra de vidrio y plástico:</strong> restauramos piezas deformadas o fracturadas con técnicas de reconstrucción y acabado para recuperar resistencia y apariencia original.</li><li><strong>Latonería:</strong> corregimos golpes, desalineaciones y deformaciones en paneles y estructuras metálicas para restablecer geometría y ajuste correcto.</li><li><strong>Pintura:</strong> aplicamos preparación de superficie, igualación de color y acabados de protección para lograr terminados uniformes y durables.</li><li><strong>Reconstrucción:</strong> ejecutamos recuperación integral de unidades con daño severo, integrando evaluación técnica, reparación estructural y validación final.</li></ul>',
    horizontalImage: '/images/img_10.webp',
    verticalImage: '/images/mantenimiento-y-reparacion-de-vehiculos-electricos-vertical.webp',
  },
  {
    slug: 'servicios-especiales',
    title: 'Servicios Especiales',
    summary:
      'Ofrecemos servicios especiales de taller y manufactura con maquinaria y personal técnico especializado para resolver requerimientos de alta precisión y procesos no convencionales.',
    description:
      '<p>Ofrecemos servicios especializados de apoyo técnico y fabricación, orientados a brindar soluciones integrales en procesos de mecanizado, conformado y verificación estructural para la industria.</p><p>Contamos con equipos y personal calificado para la operación de roladora, dobladora, corte por plasma CNC, torno y fresadora, lo que nos permite fabricar, ajustar y reparar componentes con alta precisión y calidad. Complementamos estos servicios con carro taller para atención en campo, garantizando respuesta oportuna directamente en sitio.</p><p>Adicionalmente, realizamos certificaciones y pruebas especiales de estructuras mediante ultrasonido, asegurando la integridad de los materiales, la detección temprana de fallas y el cumplimiento de estándares técnicos y de seguridad.</p><p>Nuestro enfoque está orientado a optimizar tiempos de ejecución, garantizar confiabilidad en los procesos y ofrecer soluciones adaptadas a las necesidades específicas de cada operación.</p><ul><li><strong>Roladora:</strong> conformamos láminas y perfiles curvos con precisión para fabricación y reparación de componentes estructurales.</li><li><strong>Dobladora:</strong> realizamos dobleces controlados en diferentes calibres para piezas con medidas exactas y repetibilidad en producción.</li><li><strong>Corte plasma (CNC):</strong> ejecutamos cortes automatizados de alta precisión para geometrías complejas y mejor aprovechamiento del material.</li><li><strong>Torno:</strong> mecanizamos piezas cilíndricas, ejes y componentes de ajuste fino para mantenimiento y fabricación.</li><li><strong>Fresadora:</strong> desarrollamos superficies, ranuras y mecanizados especiales con tolerancias técnicas según plano.</li><li><strong>Carro taller:</strong> brindamos atención móvil en sitio para diagnósticos y reparaciones que requieren respuesta inmediata.</li><li><strong>Certificaciones:</strong> gestionamos y respaldamos procesos de verificación técnica para cumplimiento normativo y trazabilidad.</li><li><strong>Pruebas especiales de estructuras (ultrasonido):</strong> evaluamos integridad estructural mediante ensayos no destructivos para detectar discontinuidades y prevenir fallas.</li></ul>',
    horizontalImage: '/images/img-9.webp',
    verticalImage: '/images/fabricacion-de-estructuras-metalicas-vertical.webp',
  },
  {
    slug: 'reparaciones-hidraulicas',
    title: 'Reparaciones Hidráulicas',
    summary:
      'Desarrollamos reparaciones hidráulicas integrales con diagnóstico técnico y pruebas funcionales para recuperar presión, control y confiabilidad en sistemas de trabajo pesado.',
    description:
      '<p>Ofrecemos servicios especializados en sistemas hidráulicos, orientados a garantizar el óptimo desempeño, confiabilidad y prolongación de la vida útil de los equipos.</p><p>Contamos con laboratorio de pruebas para sistemas hidráulicos, donde realizamos diagnósticos precisos que permiten evaluar condiciones de operación, detectar fallas y validar el correcto funcionamiento de los componentes.</p><p>De manera independiente, ofrecemos el servicio de diálisis de aceite, enfocado en el análisis del estado del fluido hidráulico, permitiendo identificar contaminación, desgaste interno y prevenir fallas antes de que afecten la operación del sistema.</p><p>Adicionalmente, contamos con capacidad para la fabricación de cilindros hidráulicos a la medida, cumpliendo con especificaciones técnicas exigentes y adaptándonos a las condiciones particulares de cada operación. Este servicio se complementa con la reparación de cilindros hidráulicos, orientada a la recuperación de componentes, restitución de tolerancias y aseguramiento de un desempeño confiable en campo.</p><p>Nuestro equipo técnico trabaja bajo estándares rigurosos, garantizando soluciones eficientes, reducción de tiempos de inactividad y optimización de costos de mantenimiento.</p><ul><li><strong>Laboratorio de pruebas sistemas hidráulicos:</strong> validamos bombas, válvulas y circuitos bajo condiciones controladas para confirmar desempeño y detectar desviaciones.</li><li><strong>Diálisis de aceite:</strong> analizamos condición del fluido para identificar contaminación, desgaste y variables que afectan la vida útil del sistema.</li><li><strong>Fabricación de cilindros:</strong> diseñamos y construimos cilindros hidráulicos según requerimientos de carga, carrera y tipo de operación.</li><li><strong>Reparación de cilindros:</strong> recuperamos cilindros mediante rectificación, cambio de sellos, corrección de vástagos y pruebas finales de estanqueidad y presión.</li></ul>',
    horizontalImage: '/images/repuestos-e-inventario.webp',
    verticalImage: '/images/repuestos-e-inventario-vertical.webp',
  },
];
